FROM node:18-alpine3.14 as build
WORKDIR /usr/src/bot
COPY package*.json ./

RUN npm install
RUN npm i -g nodemon
RUN apk update && \
    apk add --no-cache postgresql

COPY ./src ./
COPY ./tsconfig.json ./
COPY ./docker/entrypoint-dev.sh /

ENTRYPOINT /entrypoint-dev.sh
