FROM oven/bun:1 as build
WORKDIR /usr/src/bot
COPY package*.json ./

RUN bun install

RUN apk update && \
    apk add --no-cache postgresql

COPY ./src ./
COPY ./tsconfig.json ./
COPY ./docker/entrypoint-dev.sh /

ENTRYPOINT /entrypoint-dev.sh
