FROM node:24-alpine3.22 as build
WORKDIR /usr/src/bot
COPY package*.json ./

RUN npm install
RUN npm i -g tsc-watch
RUN apk update && \
    apk add --no-cache postgresql

COPY ./src ./
COPY ./tsconfig.json ./
COPY ./docker/entrypoint-dev.sh /

ENTRYPOINT /entrypoint-dev.sh
